### ISSUE TITLE
Be able to navigate to step definitions from libraries

### ISSUE THREAD

**Issue by gaeljw** [vbmacher/intellij-cucumber-scala#64]
# Expected behavior
Given you have some step definitions in l a common library
When you use these steps from a feature file in your project
Then the navigation from feature file to step definition should work

# Current behavior
Navigation doesn't work, steps are not identified

# Other details
I have no idea if this is doable or not but the idea would be to extend the scope in which the plugin look for `ScalaDsl` classes from "project only" to "project + libraries".

**Comment by vbmacher** [comment]
This is a good idea. I'm sure it's somehow possible, but I don't have currently time now to implement it.

**Comment by vbmacher** [comment]
@gaeljw  I was looking into this a bit, and it seems it's not that easy. Currently the plugin finds step definitions using PSI model and Scala AST. Step definitions which are found are PSI elements (e.g. `ScMethodCall` defined in the Scala IntelliJ plugin), which are then used by navigation. With this it is possible to have syntax errors and un-compilable code but still it is possible to navigate between elements.

This is different to the way how cucumber-core or cucumber-jvm-scala find step definitions, where a navigation to source is not required, but code must be compiled and loaded in a class loader. So if we wanted to utilize Scala backend from cucumber-jvm-scala to find step definitions in libraries, we fail because the library sources are not loaded in a class loader until the tests are being executed.

If we wanted to navigate to libraries, we would need to browse libraries source code actually to utilize the same mechanism as the plugin uses. If the library source code is attached to the project (e.g. IntelliJ knows how to download sources of libraries from Maven central repository), then I think this feature should actually work out of the box.

**Comment by gaeljw** [comment]
Okay I understand. Thanks for looking into it.
I'll give it a try to see if it works with sources attached because indeed the use case I was thinking is a library for which source is not published so we cannot do much with that..

**Comment by vbmacher** [comment]
Ok, thanks. If you have some results with the library with sources, please share them here so I can either close the issue or maybe fix it if it didn't work.

**Comment by gaeljw** [comment]
Hello @vbmacher, I tried with attached sources and doesn't seem to work: the step is greyed and the "ctrl+click" doesn't work: _"Cannot find declaration to go to"_.

**Comment by vbmacher** [comment]
Thanks for info, and sorry for having to wait. I'm going to look at it now.

**Comment by vbmacher** [comment]
Hm, the problem seems to be in getting the search scope where the plugin searches for step definitions:

```scala
val searchScope = module.getModuleWithDependenciesAndLibrariesScope(true)
```
I thought it should work when the library source is attached. I used gradle, and the library was attached as classic dependency. I had to tell IDEA to attach the sources since it was a local library.

But it didn't work. I have checked and the library is attached in the **project scope**, not **the module scope**. As for compilation, it works because it seems the project scope is superior to the module scope so the module sees project-scoped libraries. However, in case of "browsing" the module scope in code as in the previous code sample, the module scope doesn't see the project-scoped libraries. Weird.

I had to do this:

```scala
    val project = module.getProject
    val searchScope = module
         .getModuleWithDependenciesAndLibrariesScope(true)
         .uniteWith(ProjectScope.getLibrariesScope(project))
```

which finally worked.

**Comment by gaeljw** [comment]
This is really great news !! :+1: 
Thanks for taking the time to work on it

**Comment by vbmacher** [comment]
Thank you! I'm very glad when it is useful :)

I would like to do some unit tests before closing the issue. Do you think you can try it also? Thanks

**Comment by gaeljw** [comment]
I retrieved your latest commit and ran `gradlew runIde`, then I added a library to the project and attached sources manually, it doesn't seem to work.
But as I don't know much gradle, maybe it's more an issue with the way I wanted to test.

The source files is reachable though but the step definition in the `.feature` file is still greyed and I have the message "Cannot find declaration to go to".

Maybe I can try to build the plugin and use it in another project of mine where I know libraries are correctly setup

**Comment by vbmacher** [comment]
Interestingly I forgot to change also input filter when building index of step definitions. This index parses Scala files and saves offsets where a step definition is. The input filter decides which files to parse. Before there was:

```java
public boolean acceptInput(@NotNull VirtualFile file) {
    return super.acceptInput(file) && JavaFileElementType.isInSourceContent(file);
}
```

Apparently library even if the source is attached is not considered as "source content"... I don't understand it very good to be honest, but after removing this check it started working and I was able also to write unit tests which pass.

Can you please try it now?

**Comment by vbmacher** [comment]
Regarding how I set it up:

I had created a library first. It does not matter how you develop it, I just made sure it was published in local Maven repository. Then I created a really simple Gradle project which used this library. The `build.gradle` is as follows:

```gradle
plugins {
    id 'scala'
}

version "1.0.0"
description "Example project Cucumber for Scala"

repositories {
    mavenLocal()
    mavenCentral()
}

dependencies {
    implementation "org.scala-lang:scala-library:2.12.11"

    testImplementation "com.github.vbmacher.cucumber:cucumber-steps:1.1"
    testImplementation "io.cucumber:cucumber-scala_2.12:6.1.2"
    testImplementation "junit:junit:4.13"
}
```

The `cucumber-steps` is the library with stepdefs deployed in Maven local, including sources. 

IDEA opened this project but I had to manually attach sources of the library in "Project structure" dialog (File -> Project structure -> Libraries). Then everything started working..

**Comment by gaeljw** [comment]
Just tried latest commit, it works! Congrats!

**Comment by vbmacher** [comment]
Great! Thanks for the cooperation :) Im closing the issue now
